name: dawakhaana
description: DUHacks 4.0 Instant Medicine Delivery Application project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0' # Using the higher SDK constraint for compatibility

dependencies:
  flutter:
    sdk: flutter

  # location access enable
  location: ^8.0.0

  # UI and Icons
  cupertino_icons: ^1.0.8 # Using the latest version

  supabase_flutter: ^2.8.4
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2

  # Geolocation
  geolocator: ^13.0.2 # Using the latest version

  # Google Sign-In
  google_sign_in: ^6.2.2 # Using the latest version

  # Local Storage
  shared_preferences: ^2.5.2 # Using the latest version

  # State Management
  provider: ^6.1.2 # Added from the second version

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting
  flutter_lints: ^5.0.0 # Using the latest version for better linting support  flutter_projects: any
